//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvp3.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABSENCE
    {
        public int AbsenceId { get; set; }
        public int SubjectId { get; set; }
        public string Date { get; set; }
        public int Semester { get; set; }
        public bool CanBeExcused { get; set; }
        public bool Excused { get; set; }
        public int StudentId { get; set; }
    
        public virtual USER USER { get; set; }
        public virtual SUBJECT SUBJECT { get; set; }
    }
}
