//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvp3.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBJECT_CLASSROOM
    {
        public int SubjectId { get; set; }
        public int ClassroomId { get; set; }
        public Nullable<bool> Thesis { get; set; }
    
        public virtual CLASSROOM CLASSROOM { get; set; }
        public virtual SUBJECT SUBJECT { get; set; }
    }
}
